sudo: required
services:
  - docker
language: generic
before_install:
  - docker build -t frontend-docker-img -f Dockerfile.dev . 
script:
  - docker run -e CI=true frontend-docker-img npm run test -- --coverage